baseURL = "https://ws-zh.vercel.app"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "æœ±é¸¿çš„ä¸ªäººç½‘ç«™"
theme = "LoveIt"

[[menu.main]]
identifier = "posts"
name = "æ–‡ç« "
url = "/posts/"
weight = 1
[[menu.main]]
identifier = "notes"
name = "ç¬”è®°"
url = "/notes/"
weight = 2
[[menu.main]]
identifier = "categories"
name = "åˆ†ç±»"
url = "/categories/"
weight = 3
[[menu.main]]
identifier = "tags"
name = "æ ‡ç­¾"
url = "/tags/"
weight = 4

[params]
version = "0.2.X"

[params.app]
svgFavicon = "/logo.svg"

[params.home.profile]
avatarURL = "/avatar.webp"
subtitle = "ä¸ºäº†ä¸æŠ˜è…¾è€ŒæŠ˜è…¾ğŸ”§"
typeit = true
social = true

[params.social]
GitHub = "zhu-hong"
Bilibili = "100452267"
Email = "zhxhyy@qq.com"

[author]
name = "æœ±é¸¿"
link = "/posts/"

[params.footer]
copyright = true
since = 2021

[markup.highlight]
noClasses = false